In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/qoute_dataset.csv')

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
qoutes  = quotes.str.lower()

In [ ]:
import string
translator = str.maketrans('','',string.punctuation)
qoutes = qoutes.apply(lambda x: x.translate(translator))

In [ ]:
qoutes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size = 10000

Tokenizer = Tokenizer(num_words=vocab_size)
Tokenizer.fit_on_texts(quotes)

In [ ]:
word_index = Tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8213

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
from typing import Sequence
Sequence = Tokenizer.texts_to_sequences(quotes)

In [ ]:
for i in range(3):
  print(quotes[i])

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

In [ ]:
for i in range(3):
  print(Sequence[i])

[732, 61, 30, 19, 17, 901, 10, 7, 5, 1188, 8, 71, 290, 10, 149, 12, 835, 103, 776, 71, 290, 136]
[977, 7, 71, 902, 388, 9, 431, 21, 19, 479, 14, 299, 51, 55, 71, 2545, 136]
[1384, 14, 53, 203, 700, 3, 80, 15, 37, 36, 7, 30, 300, 92, 7, 5, 1073, 1, 104, 7, 30, 300, 126, 7, 5, 1073, 136]

In [ ]:
X = []
y = []

for seq in Sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [ ]:
len(X)

86549

In [ ]:
len(y)

86549

In [ ]:
max_len = max(len(x) for x in X)
print(max_len)

748

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X,maxlen =max_len,padding ='pre' )

In [ ]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  732],
       [   0,    0,    0, ...,    0,  732,   61],
       [   0,    0,    0, ...,  732,   61,   30],
       ...,
       [   0,    0,    0, ...,    9,   19, 1333],
       [   0,    0,    0, ...,   19, 1333,    3],
       [   0,    0,    0, ..., 1333,    3,  174]], dtype=int32)

In [ ]:
y = np.array(y)

In [ ]:
X_padded.shape

(86549, 748)

In [ ]:
y.shape

(86549,)

In [ ]:
from tensorflow.keras.utils import to_categorical

y_one_hot = to_categorical(y, num_classes=vocab_size)

In [ ]:
print(y_one_hot.shape)

(86549, 10000)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM,Dense
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
embedding_dim = 50
rnn_units = 128

In [ ]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len)
)

rnn_model.add(SimpleRNN(units= rnn_units))
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model = Sequential()

lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim, input_length = max_len)
    )
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [ ]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs = 100
batch_size = 128

In [ ]:
# early_stopping = EarlyStopping(
#     monitor='val_loss',  # Monitor validation loss
#     patience=5,          # Number of epochs with no improvement after which training will be stopped
#     restore_best_weights=True # Restore model weights from the epoch with the best value of the monitored quantity.
# )

# history_rnn = rnn_model.fit(
#     X_padded,
#     y_one_hot,
#     epochs=epochs,
#     batch_size=batch_size,
#     validation_split = 0.1,
#     callbacks=[early_stopping]
# )

In [ ]:
history_lstm = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split = 0.1,
    # callbacks=[early_stopping]
)

Epoch 1/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 38s 53ms/step - accuracy: 0.0359 - loss: 7.0644 - val_accuracy: 0.0508 - val_loss: 6.6284
Epoch 2/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.0551 - loss: 6.3001 - val_accuracy: 0.0662 - val_loss: 6.4955
Epoch 3/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.0770 - loss: 6.0367 - val_accuracy: 0.0853 - val_loss: 6.4075
Epoch 4/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 42s 52ms/step - accuracy: 0.0973 - loss: 5.7951 - val_accuracy: 0.0980 - val_loss: 6.3682
Epoch 5/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1080 - loss: 5.6060 - val_accuracy: 0.1002 - val_loss: 6.3466
Epoch 6/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.1179 - loss: 5.4315 - val_accuracy: 0.1012 - val_loss: 6.3591
Epoch 7/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.1246 - loss: 5.2958 - val_accuracy: 0.1061 - val_loss: 6.3762
Epoch 8/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.1365 - loss: 5.1298 - val_accuracy: 0.1099 - val_loss: 6.4037
Epoch 9/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.1401 - loss: 5.0014 - val_accuracy: 0.1105 - val_loss: 6.4365
Epoch 10/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.1492 - loss: 4.8714 - val_accuracy: 0.1133 - val_loss: 6.4817
Epoch 11/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.1554 - loss: 4.7478 - val_accuracy: 0.1138 - val_loss: 6.5238
Epoch 12/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.1690 - loss: 4.6052 - val_accuracy: 0.1151 - val_loss: 6.5670
Epoch 13/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.1731 - loss: 4.5007 - val_accuracy: 0.1143 - val_loss: 6.6270
Epoch 14/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1825 - loss: 4.3976 - val_accuracy: 0.1158 - val_loss: 6.6900
Epoch 15/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 51ms/step - accuracy: 0.1949 - loss: 4.2797 - val_accuracy: 0.1111 - val_loss: 6.7545
Epoch 16/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.2082 - loss: 4.1628 - val_accuracy: 0.1155 - val_loss: 6.8226
Epoch 17/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2179 - loss: 4.0735 - val_accuracy: 0.1148 - val_loss: 6.9063
Epoch 18/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2322 - loss: 3.9622 - val_accuracy: 0.1129 - val_loss: 6.9715
Epoch 19/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2444 - loss: 3.8790 - val_accuracy: 0.1154 - val_loss: 7.0454
Epoch 20/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2610 - loss: 3.7777 - val_accuracy: 0.1099 - val_loss: 7.1260
Epoch 21/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2712 - loss: 3.6949 - val_accuracy: 0.1102 - val_loss: 7.2171
Epoch 22/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2827 - loss: 3.6139 - val_accuracy: 0.1133 - val_loss: 7.3038
Epoch 23/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.2918 - loss: 3.5463 - val_accuracy: 0.1102 - val_loss: 7.3652
Epoch 24/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3049 - loss: 3.4657 - val_accuracy: 0.1080 - val_loss: 7.4444
Epoch 25/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3132 - loss: 3.4080 - val_accuracy: 0.1085 - val_loss: 7.5177
Epoch 26/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3275 - loss: 3.3326 - val_accuracy: 0.1056 - val_loss: 7.5931
Epoch 27/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3354 - loss: 3.2806 - val_accuracy: 0.1062 - val_loss: 7.6609
Epoch 28/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3423 - loss: 3.2257 - val_accuracy: 0.1064 - val_loss: 7.7348
Epoch 29/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3569 - loss: 3.1480 - val_accuracy: 0.1049 - val_loss: 7.7965
Epoch 30/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3650 - loss: 3.1030 - val_accuracy: 0.1062 - val_loss: 7.8737
Epoch 31/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3749 - loss: 3.0365 - val_accuracy: 0.1051 - val_loss: 7.9389
Epoch 32/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3826 - loss: 2.9942 - val_accuracy: 0.1044 - val_loss: 7.9944
Epoch 33/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.3908 - loss: 2.9465 - val_accuracy: 0.1025 - val_loss: 8.0725
Epoch 34/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4040 - loss: 2.8832 - val_accuracy: 0.1023 - val_loss: 8.1389
Epoch 35/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4103 - loss: 2.8395 - val_accuracy: 0.1012 - val_loss: 8.1942
Epoch 36/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4184 - loss: 2.7951 - val_accuracy: 0.1012 - val_loss: 8.2542
Epoch 37/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4274 - loss: 2.7393 - val_accuracy: 0.1011 - val_loss: 8.3074
Epoch 38/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4288 - loss: 2.7247 - val_accuracy: 0.1004 - val_loss: 8.3773
Epoch 39/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4402 - loss: 2.6632 - val_accuracy: 0.0996 - val_loss: 8.4351
Epoch 40/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4457 - loss: 2.6307 - val_accuracy: 0.0984 - val_loss: 8.4755
Epoch 41/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4579 - loss: 2.5711 - val_accuracy: 0.0994 - val_loss: 8.5520
Epoch 42/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4623 - loss: 2.5527 - val_accuracy: 0.0990 - val_loss: 8.6109
Epoch 43/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4682 - loss: 2.5069 - val_accuracy: 0.0974 - val_loss: 8.6754
Epoch 44/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4768 - loss: 2.4743 - val_accuracy: 0.0992 - val_loss: 8.7262
Epoch 45/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.4840 - loss: 2.4303 - val_accuracy: 0.0988 - val_loss: 8.7858
Epoch 46/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4903 - loss: 2.3968 - val_accuracy: 0.0961 - val_loss: 8.8357
Epoch 47/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.4928 - loss: 2.3744 - val_accuracy: 0.0958 - val_loss: 8.8972
Epoch 48/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.5024 - loss: 2.3355 - val_accuracy: 0.0974 - val_loss: 8.9521
Epoch 49/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5113 - loss: 2.2910 - val_accuracy: 0.0945 - val_loss: 9.0161
Epoch 50/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5140 - loss: 2.2664 - val_accuracy: 0.0925 - val_loss: 9.0786
Epoch 51/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5209 - loss: 2.2352 - val_accuracy: 0.0959 - val_loss: 9.1397
Epoch 52/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5261 - loss: 2.2082 - val_accuracy: 0.0932 - val_loss: 9.1764
Epoch 53/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5342 - loss: 2.1787 - val_accuracy: 0.0912 - val_loss: 9.2406
Epoch 54/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5396 - loss: 2.1395 - val_accuracy: 0.0914 - val_loss: 9.3125
Epoch 55/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.5420 - loss: 2.1177 - val_accuracy: 0.0890 - val_loss: 9.3570
Epoch 56/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.5512 - loss: 2.0796 - val_accuracy: 0.0912 - val_loss: 9.3985
Epoch 57/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.5538 - loss: 2.0685 - val_accuracy: 0.0907 - val_loss: 9.4781
Epoch 58/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5657 - loss: 2.0191 - val_accuracy: 0.0908 - val_loss: 9.5237
Epoch 59/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5635 - loss: 2.0134 - val_accuracy: 0.0910 - val_loss: 9.5788
Epoch 60/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5705 - loss: 1.9751 - val_accuracy: 0.0908 - val_loss: 9.6208
Epoch 61/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5798 - loss: 1.9470 - val_accuracy: 0.0912 - val_loss: 9.6637
Epoch 62/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5821 - loss: 1.9193 - val_accuracy: 0.0921 - val_loss: 9.7420
Epoch 63/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.5865 - loss: 1.9050 - val_accuracy: 0.0899 - val_loss: 9.7885
Epoch 64/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5905 - loss: 1.8823 - val_accuracy: 0.0915 - val_loss: 9.8290
Epoch 65/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5937 - loss: 1.8640 - val_accuracy: 0.0895 - val_loss: 9.8843
Epoch 66/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6009 - loss: 1.8227 - val_accuracy: 0.0876 - val_loss: 9.9386
Epoch 67/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6058 - loss: 1.8081 - val_accuracy: 0.0865 - val_loss: 9.9837
Epoch 68/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6101 - loss: 1.7867 - val_accuracy: 0.0878 - val_loss: 10.0450
Epoch 69/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6162 - loss: 1.7531 - val_accuracy: 0.0882 - val_loss: 10.0874
Epoch 70/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6154 - loss: 1.7558 - val_accuracy: 0.0858 - val_loss: 10.1537
Epoch 71/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6238 - loss: 1.7238 - val_accuracy: 0.0856 - val_loss: 10.2015
Epoch 72/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6276 - loss: 1.7102 - val_accuracy: 0.0865 - val_loss: 10.2554
Epoch 73/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6298 - loss: 1.6947 - val_accuracy: 0.0845 - val_loss: 10.2987
Epoch 74/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6362 - loss: 1.6627 - val_accuracy: 0.0831 - val_loss: 10.3541
Epoch 75/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6426 - loss: 1.6333 - val_accuracy: 0.0849 - val_loss: 10.3990
Epoch 76/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6412 - loss: 1.6360 - val_accuracy: 0.0861 - val_loss: 10.4548
Epoch 77/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6491 - loss: 1.6038 - val_accuracy: 0.0845 - val_loss: 10.4987
Epoch 78/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6536 - loss: 1.5898 - val_accuracy: 0.0831 - val_loss: 10.5404
Epoch 79/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6582 - loss: 1.5739 - val_accuracy: 0.0821 - val_loss: 10.6032
Epoch 80/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6600 - loss: 1.5488 - val_accuracy: 0.0837 - val_loss: 10.6368
Epoch 81/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6653 - loss: 1.5415 - val_accuracy: 0.0828 - val_loss: 10.6900
Epoch 82/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6659 - loss: 1.5180 - val_accuracy: 0.0825 - val_loss: 10.7434
Epoch 83/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6725 - loss: 1.4983 - val_accuracy: 0.0809 - val_loss: 10.7881
Epoch 84/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6756 - loss: 1.4855 - val_accuracy: 0.0841 - val_loss: 10.8541
Epoch 85/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6783 - loss: 1.4724 - val_accuracy: 0.0798 - val_loss: 10.8810
Epoch 86/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6811 - loss: 1.4498 - val_accuracy: 0.0788 - val_loss: 10.9283
Epoch 87/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6841 - loss: 1.4371 - val_accuracy: 0.0798 - val_loss: 10.9833
Epoch 88/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6881 - loss: 1.4272 - val_accuracy: 0.0771 - val_loss: 11.0003
Epoch 89/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 40s 52ms/step - accuracy: 0.6881 - loss: 1.4186 - val_accuracy: 0.0775 - val_loss: 11.0497
Epoch 90/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6971 - loss: 1.3850 - val_accuracy: 0.0776 - val_loss: 11.1014
Epoch 91/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.6968 - loss: 1.3792 - val_accuracy: 0.0794 - val_loss: 11.1490
Epoch 92/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7006 - loss: 1.3633 - val_accuracy: 0.0776 - val_loss: 11.1872
Epoch 93/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7021 - loss: 1.3544 - val_accuracy: 0.0775 - val_loss: 11.2482
Epoch 94/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7026 - loss: 1.3468 - val_accuracy: 0.0786 - val_loss: 11.2897
Epoch 95/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7099 - loss: 1.3229 - val_accuracy: 0.0793 - val_loss: 11.3317
Epoch 96/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7124 - loss: 1.3173 - val_accuracy: 0.0760 - val_loss: 11.3765
Epoch 97/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7130 - loss: 1.3097 - val_accuracy: 0.0776 - val_loss: 11.4273
Epoch 98/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7189 - loss: 1.2883 - val_accuracy: 0.0769 - val_loss: 11.4735
Epoch 99/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7208 - loss: 1.2805 - val_accuracy: 0.0763 - val_loss: 11.5085
Epoch 100/100
609/609 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.7227 - loss: 1.2643 - val_accuracy: 0.0774 - val_loss: 11.5529

In [ ]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word = {}
for word,index in word_index.items():
  index_to_word[index] = word

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
from re import VERBOSE
def predictor(model,Tokenizer,text,max_len):
  text = text.lower()

  seq = Tokenizer.texts_to_sequences([text])[0]
  seq = model.predict([seq], maxlen = max_len,padding = 'pre')


  pred = model.predict(seq,VERBOSE = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [ ]:
seed_text = 'what are you'
next_word = predictor(lstm_model,Tokenizer,seed_text,max_len)
print(next_word)

learn

In [ ]:
def generate_text(model,Tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,Tokenizer,seed_text,max_len)
    if next_word == '':
      break
    seed_text+=" " + next_word
  return seed_text

In [ ]:
seed = 'the meaning of life'
generate_text = generate_text(lstm_model,Tokenizer,seed,max_len,10)
print(generate_text)

the meaning of life is not what it is to be a man to

In [ ]:
import pickle
with open('tokenizer.pkl','wb') as f:
  pickle.dump(Tokenizer,f)

In [ ]:
with open('max_len.pkl','wb') as f:
  pickle.dump(max_len,f)